import express from 'express';
import path from 'path';
import crypto from 'crypto';
import fs from 'fs';
import { fileURLToPath } from 'url';
import mysql from 'mysql2/promise';
import { Connector, IpAddressTypes } from '@google-cloud/cloud-sql-connector';

const __filename = fileURLToPath(import.meta.url), __dirname = path.dirname(__filename);
const app = express(), PORT = process.env.PORT || 8080;
const dataPath = path.join(__dirname, 'data', 'cms.json');
const secret = process.env.CMS_SESSION_SECRET || 'change-this-local-development-session-secret';
const envPath = path.join(__dirname, '.env');
let portalPool;
app.use(express.json({ limit: '8mb' }));
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const slugify = (v = '') => v.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const hash = (password, salt = crypto.randomBytes(16).toString('hex')) => `${salt}:${crypto.scryptSync(password, salt, 64).toString('hex')}`;
const matches = (password, stored) => { const [salt, saved] = stored.split(':'); return crypto.timingSafeEqual(Buffer.from(saved, 'hex'), Buffer.from(hash(password, salt).split(':')[1], 'hex')); };
const makeToken = (user) => { const payload = Buffer.from(JSON.stringify({ id: user.id, exp: Date.now() + 43200000 })).toString('base64url'); return `${payload}.${crypto.createHmac('sha256', secret).update(payload).digest('base64url')}`; };
function authenticated(req) { try { const [payload, signature] = (req.headers.authorization || '').replace('Bearer ', '').split('.'); const expected = crypto.createHmac('sha256', secret).update(payload).digest('base64url'); if (!signature || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; const data = JSON.parse(Buffer.from(payload, 'base64url').toString()); return data.exp > Date.now() ? data : null; } catch { return null; } }
const admin = (req, res, next) => { req.admin = authenticated(req); return req.admin ? next() : res.status(401).json({ error: 'Authentication required.' }); };
const cmsSettings = () => ({ databaseProvider: process.env.CMS_DATABASE_PROVIDER || 'local', mediaProvider: process.env.CMS_MEDIA_PROVIDER || 'local', projectId: process.env.GCP_PROJECT_ID || '', instanceConnectionName: process.env.INSTANCE_CONNECTION_NAME || '', databaseName: process.env.DB_NAME || '', databaseUser: process.env.DB_USER || '', privateIp: process.env.PRIVATE_IP === 'true', bucket: process.env.GCS_BUCKET || '', publicBaseUrl: process.env.GCS_PUBLIC_BASE_URL || '', databasePasswordConfigured: Boolean(process.env.DB_PASS) })
function updateEnv(values) { let text = fs.existsSync(envPath) ? fs.readFileSync(envPath, 'utf8') : ''; for (const [key, value] of Object.entries(values)) { if (value === undefined || value === '') continue; const line = `${key}=${String(value).replace(/[\r\n]/g, '')}`; const matcher = new RegExp(`^${key}=.*$`, 'm'); text = matcher.test(text) ? text.replace(matcher, line) : `${text}${text && !text.endsWith('\n') ? '\n' : ''}${line}\n`; process.env[key] = String(value); } fs.writeFileSync(envPath, text); }
function seed() { const created = now(), user = { id: id(), name: 'CMS Administrator', email: 'admin@getafe.gov.ph', password: hash(process.env.CMS_ADMIN_PASSWORD || 'ChangeMe123!'), role: 'admin', created_at: created, updated_at: created }; const categories = ['Announcements', 'Events', 'Community', 'Updates', 'Press Release'].map(name => ({ id: id(), name, slug: slugify(name), created_at: created, updated_at: created })); const stories = [['Municipality of Getafe launches improved online public information portal', 'Updates', 'The municipality is making local services and announcements easier to access online.', '<p>The Municipality of Getafe is pleased to introduce an improved online portal for residents and visitors. The new experience brings services, local information, and official announcements together in one accessible place.</p>'], ['Community clean-up drive scheduled this September', 'Community', 'Residents, barangays, and civic groups are invited to join the coastal clean-up drive.', '<p>All residents are invited to take part in the municipality-wide clean-up drive. Please coordinate with your barangay office for assembly locations and materials.</p>'], ['Public advisory: municipal office hours', 'Announcements', 'A reminder about regular municipal office hours and service channels.', '<p>Municipal offices are open Monday through Friday during regular business hours. Online enquiries may also be sent through the contact page.</p>']]; return { users: [user], categories, media: [], news: stories.map(([title, category, excerpt, content], index) => ({ id: id(), title, slug: slugify(title), excerpt, content, featured_image: '', category_id: categories.find(c => c.name === category).id, author_id: user.id, status: 'published', published_at: new Date(Date.now() - index * 86400000).toISOString(), created_at: created, updated_at: created })) }; }
function db() { if (!fs.existsSync(dataPath)) { fs.mkdirSync(path.dirname(dataPath), { recursive: true }); fs.writeFileSync(dataPath, JSON.stringify(seed(), null, 2)); } return JSON.parse(fs.readFileSync(dataPath, 'utf8')); }
const save = data => { fs.mkdirSync(path.dirname(dataPath), { recursive: true }); fs.writeFileSync(dataPath, JSON.stringify(data, null, 2)); };
const decorate = (article, data) => ({ ...article, category: data.categories.find(c => c.id === article.category_id) || null, author: (() => { const u = data.users.find(u => u.id === article.author_id); return u && { id: u.id, name: u.name }; })() });
function uniqueSlug(items, raw, current) { const base = slugify(raw) || 'untitled'; let value = base, n = 2; while (items.some(x => x.slug === value && x.id !== current)) value = `${base}-${n++}`; return value; }
async function getPortalPool() {
  if (portalPool) return portalPool;
  if ((process.env.USER_DATABASE_PROVIDER || 'local') !== 'gcp') return null;
  const connector = new Connector();
  const options = await connector.getOptions({ instanceConnectionName: process.env.INSTANCE_CONNECTION_NAME, ipType: process.env.PRIVATE_IP === 'true' ? IpAddressTypes.PRIVATE : IpAddressTypes.PUBLIC });
  portalPool = mysql.createPool({ ...options, user: process.env.USER_DB_USER, password: process.env.USER_DB_PASS, database: process.env.USER_DB_NAME, waitForConnections: true, connectionLimit: 5 });
  return portalPool;
}
function validateArticle(body, res) { if (!body.title?.trim() || !body.excerpt?.trim() || !body.content?.trim()) { res.status(422).json({ error: 'Title, excerpt, and content are required.' }); return false; } return true; }

app.post('/api/auth/login', (req, res) => { const user = db().users.find(u => u.email === String(req.body.email || '').toLowerCase()); if (!user || !matches(req.body.password || '', user.password)) return res.status(401).json({ error: 'Invalid administrator credentials.' }); res.json({ token: makeToken(user), user: { id: user.id, name: user.name, email: user.email, role: user.role } }); });
app.post('/api/portal-auth/login', async (req, res) => { try { const pool = await getPortalPool(); if (!pool) return res.status(503).json({ error: 'Portal account database is not configured.' }); const [rows] = await pool.execute('SELECT id, name, email, password, role FROM portal_users WHERE email = ?', [String(req.body.email || '').toLowerCase()]); const user = rows[0]; if (!user || !matches(req.body.password || '', user.password)) return res.status(401).json({ error: 'Invalid email or password.' }); res.json({ user: { id: user.id, name: user.name, email: user.email, role: user.role } }); } catch { res.status(503).json({ error: 'Portal account service is unavailable.' }); } });
app.post('/api/portal-auth/register', async (req, res) => { try { const name = String(req.body.name || '').trim(), email = String(req.body.email || '').trim().toLowerCase(), password = String(req.body.password || ''); if (!name || !email || password.length < 8) return res.status(422).json({ error: 'Name, email, and a password of at least 8 characters are required.' }); const pool = await getPortalPool(); if (!pool) return res.status(503).json({ error: 'Portal account database is not configured.' }); const created = now(), user = { id: id(), name, email, password: hash(password), role: 'resident', created_at: created, updated_at: created }; await pool.execute('INSERT INTO portal_users (id, name, email, password, role, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)', [user.id, user.name, user.email, user.password, user.role, user.created_at, user.updated_at]); res.status(201).json({ user: { id: user.id, name, email, role: user.role } }); } catch (error) { res.status(error?.code === 'ER_DUP_ENTRY' ? 409 : 503).json({ error: error?.code === 'ER_DUP_ENTRY' ? 'An account with that email already exists.' : 'Portal account service is unavailable.' }); } });
app.get('/api/auth/me', admin, (req, res) => { const user = db().users.find(u => u.id === req.admin.id); res.json({ id: user.id, name: user.name, email: user.email, role: user.role }); });
app.get('/api/admin/settings', admin, (req, res) => res.json(cmsSettings()));
app.put('/api/admin/settings', admin, (req, res) => { const b = req.body || {}; if (b.databaseProvider === 'gcp' && (!b.projectId || !b.instanceConnectionName || !b.databaseName || !b.databaseUser)) return res.status(422).json({ error: 'Complete the Cloud SQL project, instance, database, and user fields.' }); updateEnv({ CMS_DATABASE_PROVIDER: b.databaseProvider, CMS_MEDIA_PROVIDER: b.mediaProvider, GCP_PROJECT_ID: b.projectId, INSTANCE_CONNECTION_NAME: b.instanceConnectionName, DB_NAME: b.databaseName, DB_USER: b.databaseUser, DB_PASS: b.databasePassword, PRIVATE_IP: String(Boolean(b.privateIp)), GCS_BUCKET: b.bucket, GCS_PUBLIC_BASE_URL: b.publicBaseUrl }); res.json({ ...cmsSettings(), restartRequired: true }); });
app.get('/api/news', (req, res) => { const data = db(), isAdmin = authenticated(req); let items = data.news.filter(n => isAdmin || (n.status === 'published' && n.published_at && new Date(n.published_at) <= new Date())); if (req.query.status && isAdmin) items = items.filter(n => n.status === req.query.status); if (req.query.category) items = items.filter(n => n.category_id === req.query.category || data.categories.find(c => c.id === n.category_id)?.slug === req.query.category); if (req.query.search) { const q = req.query.search.toLowerCase(); items = items.filter(n => `${n.title} ${n.excerpt} ${n.content}`.toLowerCase().includes(q)); } items.sort((a,b) => new Date(b.published_at || b.created_at) - new Date(a.published_at || a.created_at)); const page = Math.max(1, Number(req.query.page || 1)), limit = Math.min(24, Math.max(1, Number(req.query.limit || 9))); res.json({ items: items.slice((page - 1) * limit, page * limit).map(n => decorate(n, data)), total: items.length, page, pages: Math.ceil(items.length / limit) || 1 }); });
app.get('/api/news/:slug', (req, res) => { const data = db(), article = data.news.find(n => n.slug === req.params.slug), isAdmin = authenticated(req); if (!article || (!isAdmin && (article.status !== 'published' || new Date(article.published_at) > new Date()))) return res.status(404).json({ error: 'Article not found.' }); res.json(decorate(article, data)); });
app.post('/api/news', admin, (req, res) => { if (!validateArticle(req.body, res)) return; const data = db(), b = req.body, created = now(); const article = { id: id(), title: b.title.trim(), slug: uniqueSlug(data.news, b.slug || b.title), excerpt: b.excerpt.trim(), content: b.content.trim(), featured_image: b.featured_image || '', category_id: b.category_id || null, author_id: req.admin.id, status: b.status === 'published' ? 'published' : 'draft', published_at: b.status === 'published' ? (b.published_at || created) : null, created_at: created, updated_at: created }; data.news.push(article); save(data); res.status(201).json(decorate(article, data)); });
app.put('/api/news/:id', admin, (req, res) => { if (!validateArticle(req.body, res)) return; const data = db(), article = data.news.find(n => n.id === req.params.id); if (!article) return res.status(404).json({ error: 'Article not found.' }); const b = req.body; Object.assign(article, { title: b.title.trim(), slug: uniqueSlug(data.news, b.slug || b.title, article.id), excerpt: b.excerpt.trim(), content: b.content.trim(), featured_image: b.featured_image || '', category_id: b.category_id || null, status: b.status === 'published' ? 'published' : 'draft', published_at: b.status === 'published' ? (b.published_at || article.published_at || now()) : null, updated_at: now() }); save(data); res.json(decorate(article, data)); });
app.delete('/api/news/:id', admin, (req, res) => { const data = db(), index = data.news.findIndex(n => n.id === req.params.id); if (index < 0) return res.status(404).json({ error: 'Article not found.' }); data.news.splice(index, 1); save(data); res.status(204).end(); });
app.get('/api/categories', (req, res) => res.json(db().categories));
app.post('/api/categories', admin, (req, res) => { const data = db(), name = req.body.name?.trim(); if (!name) return res.status(422).json({ error: 'A category name is required.' }); if (data.categories.some(c => c.name.toLowerCase() === name.toLowerCase())) return res.status(409).json({ error: 'That category already exists.' }); const item = { id: id(), name, slug: uniqueSlug(data.categories, req.body.slug || name), created_at: now(), updated_at: now() }; data.categories.push(item); save(data); res.status(201).json(item); });
app.put('/api/categories/:id', admin, (req, res) => { const data = db(), item = data.categories.find(c => c.id === req.params.id), name = req.body.name?.trim(); if (!item) return res.status(404).json({ error: 'Category not found.' }); if (!name) return res.status(422).json({ error: 'A category name is required.' }); Object.assign(item, { name, slug: uniqueSlug(data.categories, req.body.slug || name, item.id), updated_at: now() }); save(data); res.json(item); });
app.delete('/api/categories/:id', admin, (req, res) => { const data = db(), index = data.categories.findIndex(c => c.id === req.params.id); if (index < 0) return res.status(404).json({ error: 'Category not found.' }); if (data.news.some(n => n.category_id === req.params.id)) return res.status(409).json({ error: 'This category is used by an article.' }); data.categories.splice(index, 1); save(data); res.status(204).end(); });
app.get('/api/media', admin, (req, res) => res.json(db().media));
app.post('/api/media', admin, (req, res) => { const { name = 'image', dataUrl = '' } = req.body, match = /^data:(image\/(jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(dataUrl); if (!match) return res.status(422).json({ error: 'Use a JPG, PNG, or WEBP image.' }); const raw = Buffer.from(match[3], 'base64'); if (raw.length > 5 * 1024 * 1024) return res.status(422).json({ error: 'Images must be 5 MB or smaller.' }); const filename = `${Date.now()}-${crypto.randomBytes(5).toString('hex')}.${match[2] === 'jpeg' ? 'jpg' : match[2]}`; fs.mkdirSync(path.join(__dirname, 'uploads'), { recursive: true }); fs.writeFileSync(path.join(__dirname, 'uploads', filename), raw); const data = db(), item = { id: id(), filename: name.replace(/[^a-zA-Z0-9._-]/g, '_'), filepath: `/uploads/${filename}`, filetype: match[1], filesize: raw.length, uploaded_by: req.admin.id, created_at: now() }; data.media.unshift(item); save(data); res.status(201).json(item); });
app.delete('/api/media/:id', admin, (req, res) => { const data = db(), index = data.media.findIndex(m => m.id === req.params.id); if (index < 0) return res.status(404).json({ error: 'Media not found.' }); if (data.news.some(n => n.featured_image === data.media[index].filepath)) return res.status(409).json({ error: 'This image is being used by an article.' }); const file = path.join(__dirname, data.media[index].filepath); if (fs.existsSync(file)) fs.unlinkSync(file); data.media.splice(index, 1); save(data); res.status(204).end(); });
app.get('/api/admin/dashboard', admin, (req, res) => { const data = db(), news = data.news.map(n => decorate(n, data)); res.json({ published: news.filter(n => n.status === 'published').length, drafts: news.filter(n => n.status === 'draft').length, recent: news.sort((a,b) => new Date(b.updated_at) - new Date(a.updated_at)).slice(0, 5) }); });
app.use(express.static(path.join(__dirname, 'dist')));
app.use((req, res) => res.sendFile(path.join(__dirname, 'dist', 'index.html')));
app.listen(PORT, '0.0.0.0', () => console.log(`Getafe Portal running on port ${PORT}`));
