import { useEffect, useState } from 'react'
import { ArrowLeft, Compass, Leaf } from 'lucide-react'
import { Link } from 'react-router-dom'

const fallback = { title: 'Man-made Mangrove Forest', excerpt: "Banacon Island is home to one of Asia's largest man-made mangrove forests.", content: `<p>Banacon is one of Getafe's nine (9) island barangays, approximately 5.0 kilometers from the town proper and reachable by a 30-minute pumpboat ride from the town's wharf. It derived its name from a fish locally called “Banak” or mullet (Mugil cephalus), a species once abundant in the area.</p><p>It has a total area of 1,775.04 hectares, of which 11.01 hectares are dry land or populated area, while the rest comprise the island's mudflats. Of these, 484.82 hectares form a man-made mangrove forest known as one of the largest in Asia.</p><p>Because of the extensive mangrove cover, residents now have more fish, seashells, and other marine products to gather or catch. Banacon is also known for its blue crabs, with an average daily catch of 300 kilograms.</p><h2>How was it possible?</h2><p>Banacon was previously devoid of trees. In the late 1950s, Eugenio Paden, known locally as Mang Denciong, collected propagules from neighboring islands and planted them in Banacon's vacant areas. When the seedlots began growing on their own, he continued planting and caring for them.</p><p>His initiative earned him the LIKAS YAMAN award in 1980, as well as recognition from the Food and Agriculture Organization. Communal and social forestry programs later expanded the work, and the first man-made mangrove forest was formally established in 1990.</p><p>Today, the plantation has a multi-layered canopy with trees ranging from 2 to 45 years old, and around 18 mangrove and associated species can be found in Banacon.</p>` }

export default function Banacon() {
  const [page, setPage] = useState(fallback)
  useEffect(() => { fetch('/api/news/man-made-mangrove-forest').then((r) => r.ok ? r.json() : Promise.reject()).then(setPage).catch(() => {}) }, [])
  return <main className="tourism-detail"><section className="tourism-detail-hero"><div className="container"><Link to="/tourism" className="tourism-detail-back"><ArrowLeft size={16} /> Discover Getafe</Link><p className="tourism-kicker"><Compass size={15} /> Banacon Island, Getafe</p><h1>{page.title}</h1><p>{page.excerpt}</p></div></section><article className="container tourism-detail-content"><div className="tourism-detail-label"><Leaf size={16} /> Nature & community</div><div className="tourism-detail-body" dangerouslySetInnerHTML={{ __html: page.content }} /></article></main>
}
