import crypto from 'node:crypto';
import { createClient } from 'redis';

const MAX_CLIENTS = 50_000;
const integer = (key, fallback, min = 0) => { const value = process.env[key]; if (value === undefined || value === '') return fallback; const number = Number.parseInt(value, 10); if (!Number.isSafeInteger(number) || number < min) throw new Error(`${key} must be an integer of at least ${min}`); return number; };
const hash = value => crypto.createHash('sha256').update(String(value)).digest('hex');
const ip = value => String(value || '').trim().replace(/^::ffff:/i, '').toLowerCase();

export const trafficConfig = Object.freeze({ redisUrl: process.env.RATE_LIMIT_REDIS_URL || '', trustedProxyCidrs: (process.env.RATE_LIMIT_TRUSTED_PROXY_CIDRS || '').split(',').map(v => v.trim()).filter(Boolean), maxQueueDepth: integer('RATE_LIMIT_MAX_QUEUE_DEPTH', 100), maxDelayedPerClient: integer('RATE_LIMIT_MAX_DELAYED_REQUESTS_PER_CLIENT', 2), maxDelayedGlobal: integer('RATE_LIMIT_MAX_GLOBAL_DELAYED_REQUESTS', 100), maxActive: integer('RATE_LIMIT_MAX_ACTIVE_REQUESTS', 200) });
export const policies = Object.freeze({
  public: { rate: integer('RATE_LIMIT_PUBLIC_PER_MINUTE', 120, 1), windowMs: 60_000, burst: integer('RATE_LIMIT_PUBLIC_BURST', 40, 1), maxDelayMs: integer('RATE_LIMIT_PUBLIC_MAX_DELAY_MS', 150), concurrency: 20 },
  normal: { rate: integer('RATE_LIMIT_API_PER_MINUTE', 120, 1), windowMs: 60_000, burst: integer('RATE_LIMIT_API_BURST', 30, 1), maxDelayMs: integer('RATE_LIMIT_API_MAX_DELAY_MS', 500), concurrency: 12 },
  sensitive: { rate: integer('RATE_LIMIT_SENSITIVE_PER_15_MINUTES', 12, 1), windowMs: 900_000, burst: integer('RATE_LIMIT_SENSITIVE_BURST', 4, 1), maxDelayMs: 0, concurrency: 3 },
  intensive: { rate: integer('RATE_LIMIT_INTENSIVE_PER_MINUTE', 12, 1), windowMs: 60_000, burst: integer('RATE_LIMIT_INTENSIVE_BURST', 4, 1), maxDelayMs: integer('RATE_LIMIT_INTENSIVE_MAX_DELAY_MS', 100), concurrency: 2 },
});
export function policyFor(req) { const path = req.originalUrl.split('?')[0]; if (/^\/api\/(auth|portal-auth)\/(login|register|forgot-password|verify-code|mfa)/.test(path)) return 'sensitive'; if (/^\/api\/media\/complete$/.test(path)) return 'normal'; if (/^\/api\/(storage|media|admin\/(reports|integrations)|citizen\/(documents|profile\/avatar))/.test(path) || (req.method === 'PUT' && path.startsWith('/uploads/'))) return 'intensive'; return path.startsWith('/api/') ? 'normal' : 'public'; }

function trustedProxy(address) { const input = ip(address).split('.').map(Number); if (input.length !== 4 || input.some(n => !Number.isInteger(n) || n < 0 || n > 255)) return false; const value = input.reduce((n, part) => (n << 8) + part, 0) >>> 0; return trafficConfig.trustedProxyCidrs.some(cidr => { const [network, rawBits] = cidr.split('/'), parts = network?.split('.').map(Number), bits = Number(rawBits); if (parts?.length !== 4 || !Number.isInteger(bits) || bits < 0 || bits > 32) return false; const base = parts.reduce((n, part) => (n << 8) + part, 0) >>> 0, mask = bits ? (0xffffffff << (32 - bits)) >>> 0 : 0; return (value & mask) === (base & mask); }); }
export function resolveClient(req, getAuthenticatedId = () => null) { const apiKey = req.get('X-API-Key'); if (apiKey && apiKey.length <= 512) return { type: 'api_key', value: hash(apiKey) }; const userId = getAuthenticatedId(req); if (userId) return { type: 'user', value: hash(`user:${userId}`) }; const upstream = ip(req.socket?.remoteAddress); const address = trustedProxy(upstream) ? ip(req.get('CF-Connecting-IP') || req.get('X-Forwarded-For')?.split(',')[0] || upstream) : upstream; return { type: 'ip', value: hash(`ip:${address}`) }; }

const LUA = `local r=redis.call('HMGET',KEYS[1],'t','u','s'); local n=tonumber(ARGV[1]); local rate=tonumber(ARGV[2]); local win=tonumber(ARGV[3]); local cap=tonumber(ARGV[4]); local t=tonumber(r[1]) or cap; local u=tonumber(r[2]) or n; local s=tonumber(r[3]) or 0; t=math.min(cap,t+math.max(0,n-u)*rate/win); local ok=t>=1; if ok then t=t-1;s=math.max(0,s-1) else s=s+1 end; local retry=ok and 0 or math.ceil((1-t)*win/rate); redis.call('HMSET',KEYS[1],'t',t,'u',n,'s',s);redis.call('PEXPIRE',KEYS[1],math.max(win*2,60000));return {ok and 1 or 0,retry,s}`;
class LocalStore { constructor() { this.items = new Map(); } async consume(key, policy, now) { if (!this.items.has(key) && this.items.size >= MAX_CLIENTS) this.items.delete(this.items.keys().next().value); const prior = this.items.get(key) || { tokens: policy.burst, updated: now, strikes: 0 }; const tokens = Math.min(policy.burst, prior.tokens + Math.max(0, now - prior.updated) * policy.rate / policy.windowMs), allowed = tokens >= 1; const result = { tokens: allowed ? tokens - 1 : tokens, updated: now, strikes: allowed ? Math.max(0, prior.strikes - 1) : prior.strikes + 1 }; this.items.set(key, result); return { allowed, retryMs: allowed ? 0 : Math.ceil((1 - tokens) * policy.windowMs / policy.rate), strikes: result.strikes, source: 'local' }; } }

export class AdaptiveTrafficProtector {
  constructor({ redisUrl = trafficConfig.redisUrl, getAuthenticatedId = () => null, getOverloaded = () => false, now = () => Date.now() } = {}) { this.redisUrl = redisUrl; this.getAuthenticatedId = getAuthenticatedId; this.getOverloaded = getOverloaded; this.now = now; this.local = new LocalStore(); this.active = 0; this.delayed = 0; this.clients = new Map(); this.redisReady = false; }
  async start() { if (!this.redisUrl) return; this.redis = createClient({ url: this.redisUrl, socket: { reconnectStrategy: retries => Math.min(5000, 100 * 2 ** retries) } }); this.redis.on('ready', () => { this.redisReady = true; }); this.redis.on('error', () => { this.redisReady = false; }); this.redis.on('end', () => { this.redisReady = false; }); await this.redis.connect().catch(() => { this.redisReady = false; }); }
  async stop() { if (this.redis?.isOpen) await this.redis.quit().catch(() => this.redis.disconnect()); }
  async consume(client, name, policy) { const key = `getafe:rl:v1:${name}:${client.value}`; if (this.redisReady) try { const data = await this.redis.eval(LUA, { keys: [key], arguments: [String(this.now()), String(policy.rate), String(policy.windowMs), String(policy.burst)] }); return { allowed: data[0] === 1, retryMs: Number(data[1]), strikes: Number(data[2]), source: 'redis' }; } catch { this.redisReady = false; } return this.local.consume(key, { ...policy, burst: Math.max(1, Math.floor(policy.burst / 2)) }, this.now()); }
  middleware() { return async (req, res, next) => { const requestPath = req.originalUrl.split('?')[0]; const isStaticAsset = !requestPath.startsWith('/api/') && (requestPath.startsWith('/assets/') || /\.(?:css|js|mjs|map|png|jpe?g|gif|svg|webp|ico|woff2?|ttf)$/i.test(requestPath)); if (['/health', '/healthz', '/ready'].includes(requestPath) || isStaticAsset) return next(); const name = policyFor(req), overloaded = this.getOverloaded(), policy = overloaded ? { ...policies[name], burst: 1, maxDelayMs: 0 } : policies[name], client = resolveClient(req, this.getAuthenticatedId), result = await this.consume(client, name, policy), retry = Math.max(1, Math.ceil(result.retryMs / 1000)); res.setHeader('RateLimit-Policy', `${policy.rate};w=${Math.ceil(policy.windowMs / 1000)}`); res.setHeader('RateLimit', `limit=${policy.rate}, remaining=${result.allowed ? Math.max(0, policy.burst - 1) : 0}, reset=${retry}`); const reject = reason => { res.setHeader('Retry-After', String(retry)); res.setHeader('Cache-Control', 'no-store'); console.warn(JSON.stringify({ event: 'traffic_control', client_id: client.value.slice(0, 12), route_policy: name, path: req.path, action: 'reject', retry_after: retry, source: result.source, reason })); return res.status(429).json({ error: "You're sending requests faster than usual. We're slowing things down briefly — please try again in a moment." }); }; if (result.allowed) return this.enter(req, res, next, client, name, policy); if (overloaded || result.strikes >= 4 || !policy.maxDelayMs || result.retryMs > policy.maxDelayMs) return reject(overloaded ? 'load_shed' : 'sustained_excess'); const pending = this.clients.get(`wait:${client.value}`) || 0; if (this.delayed >= trafficConfig.maxQueueDepth || this.delayed >= trafficConfig.maxDelayedGlobal || pending >= trafficConfig.maxDelayedPerClient) return reject('queue_full'); this.delayed++; this.clients.set(`wait:${client.value}`, pending + 1); const delay = Math.min(policy.maxDelayMs, result.retryMs) + Math.floor(Math.random() * 25); setTimeout(() => { this.delayed--; const count = (this.clients.get(`wait:${client.value}`) || 1) - 1; count ? this.clients.set(`wait:${client.value}`, count) : this.clients.delete(`wait:${client.value}`); this.enter(req, res, next, client, name, policy); }, delay); }; }
  enter(req, res, next, client, name, policy) { const key = `active:${name}:${client.value}`, current = this.clients.get(key) || 0; if (this.active >= trafficConfig.maxActive || current >= policy.concurrency) { res.setHeader('Retry-After', '1'); return res.status(429).json({ error: 'The service is busy. Please try again shortly.' }); } this.active++; this.clients.set(key, current + 1); let released = false; const release = () => { if (released) return; released = true; this.active--; const count = (this.clients.get(key) || 1) - 1; count ? this.clients.set(key, count) : this.clients.delete(key); }; res.once('finish', release); res.once('close', release); next(); }
}
