import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, Info, KeyRound, LoaderCircle, Mail } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { usePublicConfig } from '../../context/PublicConfig'
import { getPasswordPolicyChecks } from '../../passwordPolicy'
const formatCooldown = seconds => `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`
export default function ForgotPassword() {
  const publicConfig = usePublicConfig(); const minimumLength = Number(publicConfig['authentication.passwordMinLength'] || 12)
  const navigate = useNavigate(); const actionInFlight = useRef(false); const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [challenge, setChallenge] = useState(null); const [resetToken, setResetToken] = useState(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [resendAfter, setResendAfter] = useState(0)
  useEffect(() => { if (!resendAfter) { setError(value => /^Please wait \d+ seconds/.test(value) ? '' : value); return undefined }; const timer = window.setInterval(() => setResendAfter(value => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer) }, [resendAfter])
  const requestCode = async (isResend = false) => { if (actionInFlight.current || resendAfter > 0) return; actionInFlight.current = true; setLoading(true); setError(''); try { const response = await fetch('/api/auth/forgot-password', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) }); const data = await response.json(); if (!response.ok) { if (data.retryAfter) setResendAfter(data.retryAfter); throw new Error(data.error) } if (data.challengeId) { setChallenge(data.challengeId); setCode(''); setResendAfter(data.retryAfter || 300); setMessage(isResend ? 'A new verification code has been sent to your email address.' : 'If an account is registered with this email, a six-digit verification code has been sent.') } else { setMessage('If an account is registered with this email, instructions have been sent.') } } catch (e) { setError(e.message) } finally { actionInFlight.current = false; setLoading(false) } }
  const checks = getPasswordPolicyChecks(password, minimumLength)
  const submit = async (event) => { event.preventDefault(); if (actionInFlight.current || loading) return; if (!challenge && !resetToken) return requestCode(); actionInFlight.current = true; setLoading(true); setError(''); setMessage(''); try { if (resetToken && !Object.values(checks).every(Boolean)) throw new Error('Choose a stronger password that meets all the requirements.'); if (resetToken && password !== confirmPassword) throw new Error('Passwords do not match.'); const endpoint = resetToken ? '/api/auth/renew-password' : '/api/auth/forgot-password/verify'; const body = resetToken ? { resetToken, password } : { challengeId: challenge, code }; const response = await fetch(endpoint, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (resetToken) { setMessage('Password updated. You can now sign in.'); setTimeout(() => navigate('/auth/login'), 900); } else { setResetToken(data.resetToken); } } catch (e) { setError(e.message); } finally { actionInFlight.current = false; setLoading(false); } }
  const cooldownActive = resendAfter > 0 && !challenge && !resetToken && /^Please wait \d+ seconds/.test(error)
  const actualError = cooldownActive ? '' : error
  const buttonLabel = loading ? (!challenge && !resetToken ? 'Sending code…' : 'Please wait…') : cooldownActive ? `Resend in ${formatCooldown(resendAfter)}` : resetToken ? 'Next' : challenge ? 'Verify code' : 'Send code'
  return <main className="login-page login-challenge-page"><Link className="reset-back" to="/auth/login"><ArrowLeft size={16} /> Back to sign in</Link><section className="login-main"><form className={`login-card ${challenge && !resetToken ? 'check-email-card' : ''}`} onSubmit={submit}><div className="reset-icon"><KeyRound size={22} /></div><h1>{resetToken ? 'Reset your password' : challenge ? 'Check your email' : 'Reset your password'}</h1><p>{resetToken ? 'Choose a new password for your account.' : challenge ? 'Enter the six-digit code sent to your email address.' : 'Enter your email address and we will send a verification code if an account is registered with it.'}</p>{!challenge && !resetToken && <label htmlFor="reset-email">Email address<div className={`login-input-wrap ${cooldownActive ? 'is-readonly' : ''}`}><Mail size={18} /><input id="reset-email" required type="email" readOnly={cooldownActive} value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" /></div></label>}{challenge && !resetToken && <label htmlFor="reset-code">Verification code<input id="reset-code" required inputMode="numeric" value={code} onChange={(e) => setCode(e.target.value)} placeholder="Six-digit code" /></label>}{resetToken && <><label htmlFor="new-password">New password<input id="new-password" required minLength={minimumLength} maxLength="1024" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder={`At least ${minimumLength} characters`} /></label><ul className="password-requirements"><li className={checks.length ? 'met' : ''}>At least {minimumLength} characters</li><li className={checks.mixed ? 'met' : ''}>Uppercase, lowercase, and a number</li><li className={checks.symbol ? 'met' : ''}>At least one special character</li><li className={checks.common ? 'met' : ''}>Not an easy-to-guess password</li><li className={checks.size ? 'met' : ''}>1,024 characters or fewer</li></ul><label htmlFor="confirm-password">Reenter password<input id="confirm-password" required minLength={minimumLength} maxLength="1024" type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} placeholder="Reenter password" /></label></>}{actualError && <div className="login-error" role="alert">{actualError}</div>}{message && <p className={`reset-message ${challenge && !resetToken ? 'reset-info-message' : ''}`} role="status">{challenge && !resetToken && <Info size={16} aria-hidden="true" />}<span>{message}</span></p>}<button className={`login-submit ${cooldownActive ? 'is-cooldown' : ''}`} disabled={loading || cooldownActive}><>{loading && <LoaderCircle size={17} className="spin" aria-hidden="true" />}{buttonLabel}</></button>{challenge && !resetToken && <button type="button" className="reset-resend" disabled={loading || resendAfter > 0} onClick={() => requestCode(true)}>{resendAfter > 0 ? `Resend code in ${formatCooldown(resendAfter)}` : 'Resend code'}</button>}</form></section></main>
}
