import { useEffect, useState } from 'react'
import { ArrowLeft, KeyRound, Mail } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
const passwordChecks = password => ({ length: password.length >= 8, mixed: /[a-z]/.test(password) && /[A-Z]/.test(password) && /\d/.test(password), symbol: /[^A-Za-z0-9]/.test(password), common: !['password', 'password1', '12345678', 'qwerty123', 'admin123'].includes(password.toLowerCase()) })
export default function ForgotPassword() {
  const navigate = useNavigate(); const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [challenge, setChallenge] = useState(null); const [resetToken, setResetToken] = useState(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [resendAfter, setResendAfter] = useState(0)
  useEffect(() => { if (!resendAfter) return; const timer = window.setInterval(() => setResendAfter(value => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer) }, [resendAfter])
  const requestCode = async (isResend = false) => { setLoading(true); setError(''); try { const response = await fetch('/api/auth/forgot-password', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) }); const data = await response.json(); if (!response.ok) { if (data.retryAfter) setResendAfter(data.retryAfter); throw new Error(data.error) } if (data.challengeId) { setChallenge(data.challengeId); setCode(''); setResendAfter(data.retryAfter || 300); setMessage(isResend ? 'A new verification code has been sent to your email address.' : 'If an account is registered with this email, a six-digit verification code has been sent.') } else { setMessage('If an account is registered with this email, instructions have been sent.') } } catch (e) { setError(e.message) } finally { setLoading(false) } }
  const submit = async (event) => { event.preventDefault(); if (!challenge && !resetToken) return requestCode(); setLoading(true); setError(''); setMessage(''); try { const checks = passwordChecks(password); if (resetToken && (!Object.values(checks).every(Boolean))) throw new Error('Choose a stronger password that meets all the requirements.'); if (resetToken && password !== confirmPassword) throw new Error('Passwords do not match.'); const endpoint = resetToken ? '/api/auth/renew-password' : '/api/auth/forgot-password/verify'; const body = resetToken ? { resetToken, password } : { challengeId: challenge, code }; const response = await fetch(endpoint, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (resetToken) { setMessage('Password updated. You can now sign in.'); setTimeout(() => navigate('/auth/login'), 900); } else { setResetToken(data.resetToken); } } catch (e) { setError(e.message); } finally { setLoading(false); } }
  const checks = passwordChecks(password)
  return <main className="login-page login-challenge-page"><section className="login-main"><form className={`login-card ${challenge && !resetToken ? 'check-email-card' : ''}`} onSubmit={submit}><Link className="reset-back" to="/auth/login"><ArrowLeft size={16} /> Back to sign in</Link><div className="reset-icon"><KeyRound size={22} /></div><h1>{resetToken ? 'Reset your password' : challenge ? 'Check your email' : 'Reset your password'}</h1><p>{resetToken ? 'Choose a new password for your account.' : challenge ? 'Enter the six-digit code sent to your email address.' : 'Enter your email address and we will send a verification code if an account is registered with it.'}</p>{!challenge && !resetToken && <label>Email address<div className="login-input-wrap"><Mail size={18} /><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" /></div></label>}{challenge && !resetToken && <label>Verification code<input required inputMode="numeric" value={code} onChange={(e) => setCode(e.target.value)} placeholder="Six-digit code" /></label>}{resetToken && <><label>New password<input required minLength="8" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 8 characters" /></label><ul className="password-requirements"><li className={checks.length ? 'met' : ''}>At least 8 characters</li><li className={checks.mixed ? 'met' : ''}>Uppercase, lowercase, and a number</li><li className={checks.symbol ? 'met' : ''}>At least one special character</li><li className={checks.common ? 'met' : ''}>Not an easy-to-guess password</li></ul><label>Reenter password<input required minLength="8" type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} placeholder="Reenter password" /></label></>}{error && <div className="login-error" role="alert">{error}</div>}{message && <p className="reset-message" role="status">{message}</p>}<button className="login-submit" disabled={loading}>{loading ? 'Please wait…' : resetToken ? 'Next' : challenge ? 'Verify code' : 'Send code'}</button>{challenge && !resetToken && <button type="button" className="reset-resend" disabled={loading || resendAfter > 0} onClick={() => requestCode(true)}>{resendAfter > 0 ? `Resend code in ${Math.floor(resendAfter / 60)}:${String(resendAfter % 60).padStart(2, '0')}` : 'Resend code'}</button>}</form></section></main>
}
