import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, UserRound } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { barangays as fallback } from '../../data/barangays'

const slug = value => String(value || '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
const matches = (item, id) => slug(item?.id) === slug(id) || slug(item?.name) === slug(id)
export default function BarangayOfficialProfile() {
  const { id, officialSlug } = useParams()
  const [barangay, setBarangay] = useState(() => fallback.find(item => matches(item, id)) || null)
  const [official, setOfficial] = useState(null)
  useEffect(() => { Promise.all([fetch('/api/barangays'), fetch('/api/officials')]).then(async ([barangaysResponse, officialsResponse]) => { const items = barangaysResponse.ok ? await barangaysResponse.json() : fallback; const nextBarangay = items.find(item => matches(item, id)) || fallback.find(item => matches(item, id)) || null; const data = officialsResponse.ok ? await officialsResponse.json() : {}; const nextOfficial = (data.punongBarangays || []).find(item => String(item.role || '').toLowerCase().trim() === String(nextBarangay?.name || '').toLowerCase().trim()) || null; setBarangay(nextBarangay); setOfficial(nextOfficial) }).catch(() => {}) }, [id])
  if (!barangay) return <main className="section"><div className="container"><h1>Barangay not found</h1><Link to="/services/barangays">Back to Barangays</Link></div></main>
  const officialName = official?.name || barangay.captain
  const isCaptain = slug(officialName) === slug(officialSlug)
  if (!isCaptain) return <main className="section"><div className="container"><h1>Official not found</h1><Link to={`/services/barangays/${barangay.id}/officials`}>Back to Barangay Officials</Link></div></main>
  return <main className="barangay-official-profile"><section className="page-header"><div className="container official-profile-header"><Link className="barangay-detail-back" to={`/services/barangays/${barangay.id}/officials`}><ArrowLeft size={16}/> Barangay Officials</Link><span className="official-profile-icon"><img src={official?.photo || barangay.captainPhoto || barangay.photo || '/assets/brgy-user-vector/profile-circle.svg'} alt={`${officialName} profile`} onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = '/assets/brgy-user-vector/profile-circle.svg' }} /></span><p className="barangay-hero-eyebrow">PUNONG BARANGAY · GETAFE, BOHOL</p><h1>{officialName}</h1><p>{barangay.name} Barangay, Getafe, Bohol</p></div></section><div className="container official-profile-content"><div className="directory-breadcrumb"><Link to="/">Home</Link><span>›</span><Link to={`/services/barangays/${barangay.id}/officials`}>{barangay.name} Officials</Link><span>›</span><strong>{officialName}</strong></div><article className="official-public-profile"><div className="official-profile-summary"><span className="official-directory-avatar large"><UserRound size={34}/></span><div><p className="history-kicker">CURRENTLY SERVING</p><h2>{officialName}</h2><p>Punong Barangay · Barangay {barangay.name}</p></div></div><dl className="official-transparency"><div><dt>Position</dt><dd>Punong Barangay</dd></div><div><dt>Barangay</dt><dd>{barangay.name}</dd></div><div><dt>Municipality</dt><dd>Getafe, Bohol</dd></div><div><dt>Status</dt><dd>Currently serving</dd></div></dl><section><h3>About the Official</h3><p>{official?.biography || barangay.captainBio || `The Punong Barangay serves the residents of Barangay ${barangay.name} and coordinates local programs, peace and order, and barangay administration.`}</p></section><section><h3>Responsibilities</h3><ul className="official-responsibilities"><li>Barangay administration and public service delivery</li><li>Peace and order and community coordination</li><li>Implementation of barangay ordinances and programs</li><li>Coordination with the municipal government</li></ul></section></article><section className="other-officials"><h2>Other Barangay Officials</h2><Link to={`/services/barangays/${barangay.id}/officials`}>View the Barangay Officials directory <ArrowRight size={16}/></Link></section></div></main>
}
