import { useEffect, useState } from 'react'
import { ArrowLeft } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
const PLACEHOLDER = '/assets/brgy-user-vector/profile-circle.svg'
const officialId = (name) => name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
const biographyParagraphs = (value) => String(value || '').split(/\n\s*\n|(?<=[.!?])\s+(?=[A-Z][a-z])/).map((paragraph) => paragraph.trim()).filter(Boolean)
export default function OfficialProfile() {
  const { id } = useParams(); const [official, setOfficial] = useState(null)
  useEffect(() => { Promise.all([fetch('/api/officials'), fetch('/api/barangays')]).then(async ([officialsResponse, barangaysResponse]) => { if (!officialsResponse.ok) throw new Error(); const data = await officialsResponse.json(); const barangays = barangaysResponse.ok ? await barangaysResponse.json() : []; const people = [data.mayor, data.viceMayor, data.abcPresident, ...(data.sbMembers || []), ...(data.punongBarangays || []), ...(data.deptHeads || [])].filter(Boolean); const person = people.find((item) => officialId(item.name || '') === id) || null; const barangay = person && barangays.find(item => item.name?.toLowerCase() === person.role?.toLowerCase()); setOfficial(person ? { ...person, barangay } : null) }).catch(() => {}) }, [id])
  if (!official) return <main className="section"><div className="container"><h1>Official not found</h1><Link to="/info/officials">Back to Municipal Officials</Link></div></main>
  const isBarangayOfficial = Boolean(official.barangay)
  return <main className="barangay-official-page"><section className="page-header"><div className="container official-profile-header"><Link className="barangay-detail-back" to={isBarangayOfficial ? `/services/barangays/${official.barangay.id}/officials` : '/info/officials'}><ArrowLeft size={16} /> {isBarangayOfficial ? 'Barangay Officials' : 'Municipal Officials'}</Link><img className={isBarangayOfficial ? 'official-profile-photo official-profile-hero-photo' : 'official-profile-photo'} src={official.photo || PLACEHOLDER} alt={`${official.name} profile`} onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = PLACEHOLDER }} /><p className="barangay-hero-eyebrow">{isBarangayOfficial ? `PUNONG BARANGAY · ${official.barangay.name.toUpperCase()}` : 'MUNICIPALITY OF GETAFE · BOHOL'}</p><h1>{official.name}</h1><p>{isBarangayOfficial ? `Punong Barangay · ${official.barangay.name}, Getafe, Bohol` : official.role}</p>{isBarangayOfficial && <nav className="official-service-links" aria-label={`Pages for Barangay ${official.barangay.name}`}><span>Serving Barangay {official.barangay.name}</span><Link to={`/services/barangays/${official.barangay.id}`}>Barangay profile</Link><Link to={`/services/barangays/${official.barangay.id}/officials`}>Officials directory</Link><Link to={`/services/barangays/${official.barangay.id}/official`}>Official page</Link></nav>}</div></section><div className="container official-profile-content"><article className="barangay-detail-card"><p className="history-kicker">OFFICIAL PROFILE</p><h2>Biography</h2>{official.biography ? <div className="official-biography">{biographyParagraphs(official.biography).map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div> : <p>Biography information for {official.name} is not currently available.</p>}</article></div></main>
}
