-- PostgreSQL 17 baseline for the existing CMS and resident portal entities.
-- Apply this file through the migration runner; application startup never creates tables.
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name VARCHAR(160) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, role VARCHAR(32) NOT NULL DEFAULT 'admin', created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS categories (id TEXT PRIMARY KEY, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL UNIQUE, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS media (id TEXT PRIMARY KEY, original_filename VARCHAR(255) NOT NULL, storage_bucket VARCHAR(255) NOT NULL, storage_path VARCHAR(1024) NOT NULL UNIQUE, content_type VARCHAR(100) NOT NULL, file_size BIGINT NOT NULL CHECK (file_size >= 0), uploaded_by TEXT NOT NULL REFERENCES users(id), related_record_id TEXT, status VARCHAR(32) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS media_uploads (id TEXT PRIMARY KEY, storage_path VARCHAR(1024) NOT NULL UNIQUE, original_filename VARCHAR(255) NOT NULL, content_type VARCHAR(100) NOT NULL, file_size BIGINT NOT NULL CHECK (file_size >= 0), uploaded_by TEXT NOT NULL REFERENCES users(id), context VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','completed')), expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS news (id TEXT PRIMARY KEY, title VARCHAR(255) NOT NULL, slug VARCHAR(280) NOT NULL UNIQUE, excerpt TEXT NOT NULL, content TEXT NOT NULL, featured_image VARCHAR(1024) NOT NULL DEFAULT '', category_id TEXT REFERENCES categories(id) ON DELETE SET NULL, author_id TEXT NOT NULL REFERENCES users(id), status VARCHAR(32) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published')), is_important BOOLEAN NOT NULL DEFAULT FALSE, content_type VARCHAR(32) NOT NULL DEFAULT 'news', event_start_at TIMESTAMPTZ, event_end_at TIMESTAMPTZ, show_in_news BOOLEAN NOT NULL DEFAULT TRUE, show_in_upcoming BOOLEAN NOT NULL DEFAULT FALSE, show_in_events BOOLEAN NOT NULL DEFAULT FALSE, show_on_homepage BOOLEAN NOT NULL DEFAULT TRUE, published_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS site_pages (slug VARCHAR(120) PRIMARY KEY, content TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS portal_users (id TEXT PRIMARY KEY, name VARCHAR(160) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, role VARCHAR(32) NOT NULL DEFAULT 'resident', mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE, mfa_secret_encrypted TEXT, mfa_recovery_codes JSONB, mfa_verified_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS resident_profiles (user_id TEXT PRIMARY KEY REFERENCES portal_users(id) ON DELETE CASCADE, full_name VARCHAR(160) NOT NULL, birth_date DATE, sex VARCHAR(32), civil_status VARCHAR(64), nationality VARCHAR(64), mobile VARCHAR(32), house_lot VARCHAR(160), street VARCHAR(160), purok_sitio VARCHAR(160), barangay VARCHAR(160), municipality VARCHAR(100) DEFAULT 'Getafe', province VARCHAR(100) DEFAULT 'Bohol', zip_code VARCHAR(16), avatar_storage_path VARCHAR(500), verification_status VARCHAR(32) NOT NULL DEFAULT 'unverified', updated_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS applications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES portal_users(id) ON DELETE CASCADE, reference_number VARCHAR(32) NOT NULL UNIQUE, service_name VARCHAR(160) NOT NULL, status VARCHAR(48) NOT NULL DEFAULT 'draft', payment_status VARCHAR(32) NOT NULL DEFAULT 'not_required', submitted_at TIMESTAMPTZ, last_updated TIMESTAMPTZ NOT NULL, details JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS appointments (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES portal_users(id) ON DELETE CASCADE, application_id TEXT REFERENCES applications(id) ON DELETE SET NULL, department VARCHAR(160) NOT NULL, service VARCHAR(160) NOT NULL, appointment_at TIMESTAMPTZ NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'scheduled', created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY, application_id TEXT NOT NULL REFERENCES applications(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES portal_users(id) ON DELETE CASCADE, amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0), method VARCHAR(64), status VARCHAR(32) NOT NULL DEFAULT 'pending', official_receipt VARCHAR(64), created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES portal_users(id) ON DELETE CASCADE, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, read_at TIMESTAMPTZ, archived_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS system_settings (setting_key VARCHAR(100) PRIMARY KEY, value TEXT NOT NULL, updated_by TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, action VARCHAR(100) NOT NULL, category VARCHAR(100) NOT NULL, setting_key VARCHAR(100) NOT NULL, old_value TEXT, new_value TEXT, ip_address VARCHAR(100), correlation_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings_lock (id INTEGER PRIMARY KEY CHECK (id = 1));
INSERT INTO settings_lock (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
CREATE TABLE IF NOT EXISTS auth_state (state_key TEXT PRIMARY KEY, value TEXT NOT NULL, expires_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS news_public_listing_idx ON news(status, published_at);
CREATE INDEX IF NOT EXISTS media_uploads_owner_status_idx ON media_uploads(uploaded_by, status, expires_at);
CREATE INDEX IF NOT EXISTS applications_user_idx ON applications(user_id);
CREATE INDEX IF NOT EXISTS appointments_user_idx ON appointments(user_id);
CREATE INDEX IF NOT EXISTS notifications_user_idx ON notifications(user_id);
CREATE INDEX IF NOT EXISTS audit_created_at_idx ON audit_logs(created_at DESC);
