import { useEffect, useState } from 'react'

const statuses = ['submitted', 'identity_verified', 'under_review', 'processing', 'completed', 'additional_information_required', 'partially_completed', 'rejected_unable_to_delete', 'cancelled']
const label = value => value.replaceAll('_', ' ')
const api = (url, options = {}) => fetch(url, { credentials: 'include', headers: { 'Content-Type': 'application/json' }, ...options }).then(async response => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'Request failed'); return body })

export default function AdminPrivacyRequests({ onNotice }) {
  const [items, setItems] = useState([]), [selected, setSelected] = useState(null), [status, setStatus] = useState('under_review'), [note, setNote] = useState(''), [loading, setLoading] = useState(true)
  const load = () => { setLoading(true); api('/api/admin/privacy-requests').then(setItems).catch(error => onNotice(error.message)).finally(() => setLoading(false)) }
  useEffect(load, [])
  const save = async event => { event.preventDefault(); try { await api(`/api/admin/privacy-requests/${selected.id}`, { method: 'PATCH', body: JSON.stringify({ status, note }) }); onNotice('Privacy request updated.'); setSelected(null); setNote(''); load() } catch (error) { onNotice(error.message) } }
  if (loading) return <p className="cms-muted">Loading privacy requests…</p>
  return <section className="privacy-admin"><div className="cms-title"><div><h1>Data Privacy Requests</h1></div></div><p className="cms-muted">Review requests. Account/profile data and uploaded files may be eligible; applications, permits, certificates, payments, correspondence, and audit records remain protected until an authorized review confirms otherwise.</p>{items.length ? <div className="privacy-admin-list">{items.map(item => <button type="button" className="privacy-admin-item" key={item.id} onClick={() => { setSelected(item); setStatus(item.status); setNote(item.review_note || '') }}><span><strong>{item.id.slice(0, 8).toUpperCase()}</strong><small>{item.request_type} · {label(item.scope)}</small></span><span><b>{label(item.status)}</b><small>{new Date(item.created_at).toLocaleDateString('en-PH')}</small></span></button>)}</div> : <div className="cms-empty"><h2>No privacy requests</h2><p>Submitted citizen privacy requests will appear here.</p></div>}{selected && <div className="privacy-admin-editor"><form onSubmit={save}><h2>Review request {selected.id.slice(0, 8).toUpperCase()}</h2><p><strong>Scope:</strong> {label(selected.scope)}</p><p><strong>Submitted:</strong> {new Date(selected.created_at).toLocaleString('en-PH')}</p><p className="cms-muted"><strong>Protected systems:</strong> official applications, permits, certificates, payments, correspondence, and audit history. Review before taking any action.</p><label>Status<select value={status} onChange={event => setStatus(event.target.value)}>{statuses.map(value => <option key={value} value={value}>{label(value)}</option>)}</select></label><label>Reason or update note<textarea value={note} onChange={event => setNote(event.target.value)} required rows="4" placeholder="Explain retained records or the action taken in plain language."/></label><div><button type="button" onClick={() => setSelected(null)}>Cancel</button><button className="cms-primary" type="submit">Save update</button></div></form></div>}</section>
}
