import { useEffect, useMemo, useState } from 'react'
import { Archive, Check, ChevronLeft, ChevronRight, KeyRound, Plus, Search, ShieldCheck, Users, X } from 'lucide-react'
import './AdminAccessManagement.css'

const request = async (url, options = {}) => {
  const response = await fetch(url, { ...options, credentials: 'include', headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'GetafeCitizenPortal', ...options.headers } })
  const body = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`)
  return body
}

const title = value => String(value || '').replace(/_/g, ' ').replace(/\b\w/g, letter => letter.toUpperCase())
const timestamp = value => value ? new Date(value).toLocaleString('en-PH', { timeZone: 'Asia/Manila', dateStyle: 'medium', timeStyle: 'short' }) : 'Not available'
const PAGE_SIZE = 10

function Pager({ page, pages, setPage }) {
  if (pages <= 1) return null
  return <div className="access-pager"><button type="button" disabled={page === 1} onClick={() => setPage(page - 1)} aria-label="Previous page"><ChevronLeft size={16}/></button><span>Page {page} of {pages}</span><button type="button" disabled={page === pages} onClick={() => setPage(page + 1)} aria-label="Next page"><ChevronRight size={16}/></button></div>
}

function Dialog({ title: heading, subtitle, onClose, wide = false, children }) {
  return <div className="access-dialog-backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}><section className={`access-dialog${wide ? ' wide' : ''}`} role="dialog" aria-modal="true" aria-labelledby="access-dialog-title"><header><div><h2 id="access-dialog-title">{heading}</h2>{subtitle && <p>{subtitle}</p>}</div><button type="button" className="access-dialog-close" onClick={onClose} aria-label="Close"><X size={19}/></button></header>{children}</section></div>
}

function CheckboxList({ items, selected, onChange, labelKey = 'name', disabled }) {
  const values = new Set(selected)
  return <div className="access-check-list">{items.map(item => <label key={item.id}><input type="checkbox" checked={values.has(item.id)} disabled={disabled?.(item)} onChange={event => onChange(event.target.checked ? [...values, item.id] : [...values].filter(id => id !== item.id))}/><span><strong>{item[labelKey]}</strong>{item.description && <small>{item.description}</small>}</span></label>)}</div>
}

function UserDialog({ user, data, currentUser, onClose, reload, setNotice }) {
  const [tab, setTab] = useState('profile')
  const [groupIds, setGroupIds] = useState(user.groups.map(group => group.id))
  const [effective, setEffective] = useState(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  useEffect(() => { if (tab === 'effective' && !effective) request(`/api/admin/access/users/${encodeURIComponent(user.id)}/effective`).then(setEffective).catch(error => setError(error.message)) }, [tab, effective, user.id])
  const saveGroups = async () => {
    setBusy(true); setError('')
    try { await request(`/api/admin/access/users/${encodeURIComponent(user.id)}/groups`, { method: 'PUT', body: JSON.stringify({ group_ids: groupIds }) }); await reload(); setNotice('Group membership saved. Effective access has been updated.'); onClose() } catch (error) { setError(error.message) } finally { setBusy(false) }
  }
  const activity = data.activity.filter(item => item.target_id === user.id || String(item.new_value || '').includes(user.id) || String(item.previous_value || '').includes(user.id))
  return <Dialog title={user.name} subtitle={user.email} onClose={onClose} wide><div className="access-detail-tabs" role="tablist">{['profile', 'groups', 'effective', 'activity'].map(item => <button type="button" role="tab" aria-selected={tab === item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item === 'groups' ? 'Group Membership' : title(item)}</button>)}</div>{error && <div className="access-feedback error">{error}</div>}<div className="access-dialog-body">
    {tab === 'profile' && <dl className="access-profile"><div><dt>Full name</dt><dd>{user.name}</dd></div><div><dt>Email address</dt><dd>{user.email}</dd></div><div><dt>Account role</dt><dd>{title(user.role)}</dd></div><div><dt>Status</dt><dd>{user.role === 'disabled' ? 'Disabled' : 'Active'}</dd></div></dl>}
    {tab === 'groups' && <><p className="access-help">Membership is the source of this user’s permissions. Changes apply immediately.</p><CheckboxList items={data.groups.filter(group => !group.archived_at)} selected={groupIds} onChange={setGroupIds} disabled={() => user.id === currentUser.id}/><div className="access-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button type="button" disabled={busy || user.id === currentUser.id} onClick={saveGroups}>{busy ? 'Saving…' : 'Save membership'}</button></div></>}
    {tab === 'effective' && (!effective ? <p>Calculating effective access…</p> : <div className="effective-list">{data.permissions.map(permission => { const entry = effective.permissions.find(item => item.id === permission.id); return <article key={permission.id}><div><strong>{permission.label}</strong><code>{permission.id}</code></div><span className={entry?.allowed ? 'allowed' : 'denied'}>{entry?.allowed ? 'Allowed' : 'Not allowed'}</span>{entry?.sources?.length ? <small>Source: {entry.sources.map(source => `${source.group} → ${permission.id}${source.policies.length ? ` (${source.policies.map(policy => policy.name).join(', ')})` : ''}`).join('; ')}</small> : <small>No group grants this permission.</small>}</article> })}</div>)}
    {tab === 'activity' && <AuditTable items={activity}/>} 
  </div></Dialog>
}

function GroupDialog({ group, data, onClose, reload, setNotice }) {
  const [detail, setDetail] = useState(null)
  const [tab, setTab] = useState('overview')
  const [form, setForm] = useState({ name: group.name, description: group.description || '', enabled: Boolean(group.enabled) })
  const [memberIds, setMemberIds] = useState([])
  const [permissionIds, setPermissionIds] = useState([])
  const [policyIds, setPolicyIds] = useState([])
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  useEffect(() => { request(`/api/admin/access/groups/${encodeURIComponent(group.id)}`).then(result => { setDetail(result); setMemberIds(result.members.map(item => item.user_id)); setPermissionIds(result.permissions.map(item => item.id)); setPolicyIds(result.policies.map(item => item.id)) }).catch(error => setError(error.message)) }, [group.id])
  const save = async (path, body, message) => { setBusy(true); setError(''); try { await request(path, { method: path.endsWith(group.id) ? 'PATCH' : 'PUT', body: JSON.stringify(body) }); await reload(); setNotice(message); onClose() } catch (error) { setError(error.message) } finally { setBusy(false) } }
  const archive = async () => { if (!window.confirm(`Archive ${group.name}? The group must have no members.`)) return; setBusy(true); try { await request(`/api/admin/access/groups/${group.id}`, { method: 'DELETE' }); await reload(); setNotice('Group archived.'); onClose() } catch (error) { setError(error.message) } finally { setBusy(false) } }
  return <Dialog title={group.name} subtitle={`${group.member_count} member${group.member_count === 1 ? '' : 's'} · ${group.permission_count} permissions`} onClose={onClose} wide><div className="access-detail-tabs" role="tablist">{['overview', 'members', 'permissions', 'policies', 'activity'].map(item => <button type="button" role="tab" aria-selected={tab === item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{title(item)}</button>)}</div>{error && <div className="access-feedback error">{error}</div>}<div className="access-dialog-body">
    {!detail ? <p>Loading group details…</p> : <>
      {tab === 'overview' && <div className="access-form"><label>Group name<input value={form.name} disabled={Boolean(group.system_group)} onChange={event => setForm({ ...form, name: event.target.value })}/></label><label>Description<textarea rows="4" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })}/></label><label className="access-switch"><input type="checkbox" checked={form.enabled} disabled={Boolean(group.system_group)} onChange={event => setForm({ ...form, enabled: event.target.checked })}/><span>Group enabled</span></label><div className="access-actions split">{!group.system_group && <button type="button" className="danger" onClick={archive} disabled={busy}><Archive size={16}/>Archive group</button>}<button type="button" onClick={() => save(`/api/admin/access/groups/${group.id}`, form, 'Group details saved.')} disabled={busy}>{busy ? 'Saving…' : 'Save changes'}</button></div></div>}
      {tab === 'members' && <><p className="access-help">Selected users inherit this group’s permissions and policies.</p><CheckboxList items={data.users} selected={memberIds} onChange={setMemberIds} labelKey="name"/><div className="access-actions"><button type="button" onClick={() => save(`/api/admin/access/groups/${group.id}/members`, { user_ids: memberIds }, 'Group members saved.')} disabled={busy}>Save members</button></div></>}
      {tab === 'permissions' && <><p className="access-help">Permissions define what members can do. Sensitive grants require equivalent authority.</p>{Object.entries(data.permissions.reduce((result, permission) => ({ ...result, [permission.category]: [...(result[permission.category] || []), permission] }), {})).map(([category, permissions]) => <section className="permission-category" key={category}><h3>{category}</h3><CheckboxList items={permissions} selected={permissionIds} onChange={setPermissionIds} labelKey="label"/></section>)}<div className="access-actions"><button type="button" onClick={() => save(`/api/admin/access/groups/${group.id}/permissions`, { permission_ids: permissionIds }, 'Group permissions saved.')} disabled={busy}>Save permissions</button></div></>}
      {tab === 'policies' && <><p className="access-help">Policies restrict when an inherited permission may be used.</p><CheckboxList items={data.policies} selected={policyIds} onChange={setPolicyIds}/><div className="access-actions"><button type="button" onClick={() => save(`/api/admin/access/groups/${group.id}/policies`, { policy_ids: policyIds }, 'Group policies saved.')} disabled={busy}>Save policies</button></div></>}
      {tab === 'activity' && <AuditTable items={detail.activity}/>} 
    </>}
  </div></Dialog>
}

function AuditTable({ items }) {
  if (!items.length) return <p className="access-empty">No recorded changes.</p>
  return <div className="access-table-wrap"><table className="access-table"><thead><tr><th>Action</th><th>Actor</th><th>Target</th><th>Changed at</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{title(item.action)}</strong></td><td><code>{item.actor_id}</code></td><td>{title(item.target_type)} · <code>{item.target_id}</code></td><td>{timestamp(item.created_at)}</td></tr>)}</tbody></table></div>
}

export default function AdminAccessManagement({ currentUser, initialTab = 'users' }) {
  const [tab, setTab] = useState(initialTab)
  const [data, setData] = useState(null)
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('all')
  const [page, setPage] = useState(1)
  const [selectedUser, setSelectedUser] = useState(null)
  const [selectedGroup, setSelectedGroup] = useState(null)
  const [createType, setCreateType] = useState(null)
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const [groupForm, setGroupForm] = useState({ name: '', description: '', permission_ids: [] })
  const [userForm, setUserForm] = useState({ name: '', email: '', password: '', role: 'staff', group_ids: [] })
  const [policyForm, setPolicyForm] = useState({ name: '', description: '', effect: 'allow', permission_id: '', resource_field: 'department_id', user_field: 'department_id' })
  const load = async () => { setError(''); try { setData(await request('/api/admin/access')) } catch (error) { setError(error.message) } }
  useEffect(() => { load() }, [])
  useEffect(() => { setPage(1) }, [query, status, tab])
  const tabPermissions = { users: 'users.view', groups: 'groups.manage', permissions: 'permissions.manage', policies: 'policies.manage', audit: 'audit.view' }
  const tabs = ['users', 'groups', 'permissions', 'policies', 'audit'].filter(item => currentUser.permissions?.includes(tabPermissions[item]))
  const filtered = useMemo(() => {
    const list = tab === 'groups' ? data?.groups || [] : data?.users || []
    return list.filter(item => `${item.name} ${item.email || ''}`.toLowerCase().includes(query.toLowerCase()) && (status === 'all' || (tab === 'groups' ? status === (item.enabled ? 'enabled' : 'disabled') : status === (item.role === 'disabled' ? 'disabled' : 'active'))))
  }, [data, query, status, tab])
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)), visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE)
  const createGroup = async event => { event.preventDefault(); setBusy(true); setError(''); try { await request('/api/admin/access/groups', { method: 'POST', body: JSON.stringify(groupForm) }); setCreateType(null); setGroupForm({ name: '', description: '', permission_ids: [] }); await load(); setNotice('Group created and permissions assigned.') } catch (error) { setError(error.message) } finally { setBusy(false) } }
  const createUser = async event => { event.preventDefault(); setBusy(true); setError(''); try { const result = await request('/api/admin/users', { method: 'POST', body: JSON.stringify(userForm) }); if (userForm.group_ids.length) await request(`/api/admin/access/users/${result.id}/groups`, { method: 'PUT', body: JSON.stringify({ group_ids: userForm.group_ids }) }); setCreateType(null); setUserForm({ name: '', email: '', password: '', role: 'staff', group_ids: [] }); await load(); setNotice(result.warning || 'Account created and group access assigned.') } catch (error) { setError(error.message) } finally { setBusy(false) } }
  const createPolicy = async event => { event.preventDefault(); setBusy(true); setError(''); try { await request('/api/admin/access/policies', { method: 'POST', body: JSON.stringify({ name: policyForm.name, description: policyForm.description, effect: policyForm.effect, permission_id: policyForm.permission_id || null, condition: { resource_field: policyForm.resource_field, user_field: policyForm.user_field } }) }); setCreateType(null); await load(); setNotice('Policy created. Assign it from a group’s Policies tab.') } catch (error) { setError(error.message) } finally { setBusy(false) } }
  return <div className="access-management"><div className="access-title"><div><span>Administration</span><h1>Access Management</h1><p>Manage users centrally through groups, permissions, and conditional policies.</p></div>{['users', 'groups', 'policies'].includes(tab) && <button type="button" onClick={() => setCreateType(tab === 'users' ? 'user' : tab === 'groups' ? 'group' : 'policy')}><Plus size={17}/>{tab === 'users' ? 'Add user' : tab === 'groups' ? 'Create group' : 'Create policy'}</button>}</div>
    <nav className="access-tabs" aria-label="Access management sections" role="tablist">{tabs.map(item => <button type="button" role="tab" aria-selected={tab === item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item === 'audit' ? 'Audit Log' : title(item)}</button>)}</nav>
    {notice && <div className="access-feedback"><Check size={17}/>{notice}<button type="button" onClick={() => setNotice('')} aria-label="Dismiss"><X size={15}/></button></div>}{error && <div className="access-feedback error">{error}</div>}
    {!data ? !error && <p>Loading access controls…</p> : <>
      {['users', 'groups'].includes(tab) && <><div className="access-toolbar"><label><Search size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder={`Search ${tab}…`} aria-label={`Search ${tab}`}/></label><select value={status} onChange={event => setStatus(event.target.value)}><option value="all">All statuses</option><option value={tab === 'groups' ? 'enabled' : 'active'}>{tab === 'groups' ? 'Enabled' : 'Active'}</option><option value="disabled">Disabled</option></select></div><div className="access-table-wrap"><table className="access-table"><thead><tr>{tab === 'users' ? <><th>User</th><th>Role</th><th>Groups</th><th>Status</th><th>Action</th></> : <><th>Group</th><th>Members</th><th>Permissions</th><th>Status</th><th>Action</th></>}</tr></thead><tbody>{visible.map(item => tab === 'users' ? <tr key={item.id}><td><div className="access-person"><span>{item.name.slice(0, 1).toUpperCase()}</span><div><strong>{item.name}{item.id === currentUser.id ? ' (you)' : ''}</strong><small>{item.email}</small></div></div></td><td>{title(item.role)}</td><td><div className="access-chips">{item.groups.length ? item.groups.map(group => <span key={group.id}>{group.name}</span>) : <em>No groups</em>}</div></td><td><b className={`access-status ${item.role === 'disabled' ? 'disabled' : 'enabled'}`}>{item.role === 'disabled' ? 'Disabled' : 'Active'}</b></td><td><button type="button" className="link" onClick={() => setSelectedUser(item)}>View access</button></td></tr> : <tr key={item.id}><td><div><strong>{item.name}</strong><small className="table-description">{item.description || 'No description'}</small></div></td><td>{item.member_count}</td><td>{item.permission_count}</td><td><b className={`access-status ${item.enabled ? 'enabled' : 'disabled'}`}>{item.enabled ? 'Enabled' : 'Disabled'}</b></td><td><button type="button" className="link" onClick={() => setSelectedGroup(item)}>Manage</button></td></tr>)}</tbody></table>{!visible.length && <p className="access-empty">No {tab} match the current filters.</p>}</div><Pager page={page} pages={pages} setPage={setPage}/></>}
      {tab === 'permissions' && <div className="permission-directory">{Object.entries(data.permissions.reduce((result, permission) => ({ ...result, [permission.category]: [...(result[permission.category] || []), permission] }), {})).map(([category, permissions]) => <section key={category}><h2>{category}</h2><div>{permissions.map(permission => <article key={permission.id}><span className="permission-icon"><KeyRound size={17}/></span><div><strong>{permission.label}{permission.sensitive ? <b>Sensitive</b> : null}</strong><code>{permission.id}</code><p>{permission.description}</p></div></article>)}</div></section>)}</div>}
      {tab === 'policies' && <div className="access-table-wrap"><table className="access-table"><thead><tr><th>Policy</th><th>Permission</th><th>Effect</th><th>Condition</th><th>Status</th></tr></thead><tbody>{data.policies.map(policy => <tr key={policy.id}><td><strong>{policy.name}</strong><small className="table-description">{policy.description}</small></td><td><code>{policy.permission_id || 'All group permissions'}</code></td><td><b className={`policy-effect ${policy.effect}`}>{title(policy.effect)}</b></td><td><code>{JSON.stringify(policy.condition)}</code></td><td><b className={`access-status ${policy.enabled ? 'enabled' : 'disabled'}`}>{policy.enabled ? 'Enabled' : 'Disabled'}</b></td></tr>)}</tbody></table>{!data.policies.length && <p className="access-empty">No policies have been created.</p>}</div>}
      {tab === 'audit' && <AuditTable items={data.activity}/>} 
    </>}
    {selectedUser && <UserDialog user={selectedUser} data={data} currentUser={currentUser} onClose={() => setSelectedUser(null)} reload={load} setNotice={setNotice}/>} {selectedGroup && <GroupDialog group={selectedGroup} data={data} onClose={() => setSelectedGroup(null)} reload={load} setNotice={setNotice}/>} 
    {createType === 'group' && <Dialog title="Create group" subtitle="Users inherit every permission and policy assigned to this group." onClose={() => setCreateType(null)} wide><form className="access-dialog-body access-form" onSubmit={createGroup}><label>Group name<input required pattern="[A-Za-z][A-Za-z0-9_-]{2,79}" value={groupForm.name} onChange={event => setGroupForm({ ...groupForm, name: event.target.value })} placeholder="Staff_Support"/></label><label>Description<textarea rows="3" required value={groupForm.description} onChange={event => setGroupForm({ ...groupForm, description: event.target.value })}/></label><h3>Permissions</h3>{Object.entries(data.permissions.reduce((result, permission) => ({ ...result, [permission.category]: [...(result[permission.category] || []), permission] }), {})).map(([category, permissions]) => <section className="permission-category" key={category}><h4>{category}</h4><CheckboxList items={permissions} selected={groupForm.permission_ids} onChange={permission_ids => setGroupForm({ ...groupForm, permission_ids })} labelKey="label"/></section>)}<div className="access-actions"><button type="button" className="secondary" onClick={() => setCreateType(null)}>Cancel</button><button disabled={busy}>{busy ? 'Creating…' : 'Create group'}</button></div></form></Dialog>}
    {createType === 'user' && <Dialog title="Add municipal user" subtitle="Grant delegated access through one or more groups." onClose={() => setCreateType(null)}><form className="access-dialog-body access-form" onSubmit={createUser}><label>Full name<input required maxLength="160" value={userForm.name} onChange={event => setUserForm({ ...userForm, name: event.target.value })}/></label><label>Email address<input required type="email" value={userForm.email} onChange={event => setUserForm({ ...userForm, email: event.target.value })}/></label><label>Temporary password<input required type="password" minLength="12" maxLength="128" value={userForm.password} onChange={event => setUserForm({ ...userForm, password: event.target.value })}/></label><label>Account type<select value={userForm.role} onChange={event => setUserForm({ ...userForm, role: event.target.value })}><option value="staff">Municipal staff</option><option value="content_manager">Content manager</option><option value="it_support">IT support</option><option value="admin">Administrator</option></select></label><div><h3>Group membership</h3><CheckboxList items={data.groups.filter(group => group.enabled && !group.archived_at)} selected={userForm.group_ids} onChange={group_ids => setUserForm({ ...userForm, group_ids })}/></div><div className="access-actions"><button type="button" className="secondary" onClick={() => setCreateType(null)}>Cancel</button><button disabled={busy || !userForm.group_ids.length}>{busy ? 'Creating…' : 'Create account'}</button></div></form></Dialog>}
    {createType === 'policy' && <Dialog title="Create policy" subtitle="Policies restrict a group permission to matching request and user context." onClose={() => setCreateType(null)}><form className="access-dialog-body access-form" onSubmit={createPolicy}><label>Policy name<input required maxLength="120" value={policyForm.name} onChange={event => setPolicyForm({ ...policyForm, name: event.target.value })}/></label><label>Description<textarea rows="3" value={policyForm.description} onChange={event => setPolicyForm({ ...policyForm, description: event.target.value })}/></label><label>Permission<select required value={policyForm.permission_id} onChange={event => setPolicyForm({ ...policyForm, permission_id: event.target.value })}><option value="">Select permission</option>{data.permissions.map(permission => <option key={permission.id} value={permission.id}>{permission.id}</option>)}</select></label><label>Effect<select value={policyForm.effect} onChange={event => setPolicyForm({ ...policyForm, effect: event.target.value })}><option value="allow">Allow only when condition matches</option><option value="deny">Deny when condition matches</option></select></label><div className="access-form-row"><label>Resource field<input required value={policyForm.resource_field} onChange={event => setPolicyForm({ ...policyForm, resource_field: event.target.value })}/></label><label>User field<input required value={policyForm.user_field} onChange={event => setPolicyForm({ ...policyForm, user_field: event.target.value })}/></label></div><p className="access-help">Example: request department_id must equal the signed-in user’s department_id.</p><div className="access-actions"><button type="button" className="secondary" onClick={() => setCreateType(null)}>Cancel</button><button disabled={busy}>{busy ? 'Creating…' : 'Create policy'}</button></div></form></Dialog>}
  </div>
}
